# Generated by Django 5.1.1 on 2024-11-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_beauty_customer_man_woman_delete_computers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man',
        ),
        migrations.DeleteModel(
            name='Woman',
        ),
    ]
