# Generated by Django 5.1.1 on 2024-11-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_man_delete_woman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasmetika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='kasmetika/')),
            ],
        ),
    ]
