# Generated by Django 5.1.1 on 2024-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_kasmetika'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beauty',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='free',
            old_name='bio',
            new_name='description',
        ),
    ]
