# Generated by Django 5.1.1 on 2024-11-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_bio_beauty_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beauty',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='description',
            new_name='bio',
        ),
    ]
