# Generated by Django 5.1.1 on 2024-11-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_description_beauty_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasmetika',
            name='price',
        ),
    ]
