# Generated by Django 5.1.1 on 2024-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_kasmetika_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('img', models.ImageField(upload_to='computer/')),
            ],
        ),
        migrations.CreateModel(
            name='Kiyimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='kiyimlar/')),
            ],
        ),
        migrations.DeleteModel(
            name='Kasmetika',
        ),
        migrations.RemoveField(
            model_name='free',
            name='description',
        ),
    ]
